baseURL = 'https://new-sevenslegal.netlify.app'
languageCode = 'en-us'
title = 'Sevens Legal'
theme = 'netlify-basic'

[permalinks]
  posts = '/:slug/'
[menu]
[[menu.main]]
    name = "Home"
    identifier = "home"
	weight = -150
    url = "/"
[[menu.main]]
    name = "Attorneys"
    identifier = "attorneys"
	weight = -140
    url = "/attorneys/"
[[menu.main]]
    name = "Criminal Law"
	weight = -130
    url = "/criminal/"
[[menu.main]]
weight = -120
    name = "Testimonials"
    url = "/testimonials/"
[[menu.main]]
    name = "Blog"
	weight = -110
    url = "/blog/"
[[menu.main]]
weight = -100
    name = "Contact"
    url = "/contact/"