baseURL = 'https://new-sevenslegal.netlify.app'
languageCode = 'en-us'
title = 'Sevens Legal'
theme = 'netlify-basic'

[[menu.main]]
    name = "Home"
    identifier = "home"
	weight = -150
    url = "{{ .Site.BaseUrl }}"
[[menu.main]]
    name = "Attorneys"
    identifier = "attorneys"
	weight = -140
    url = "{{ .Site.BaseUrl }}/attorneys/"
[[menu.main]]
    name = "Criminal Law"
	weight = -130
    url = "{{ .Site.BaseUrl }}/criminal/"
[[menu.main]]
weight = -120
    name = "Testimonials"
    url = "{{ .Site.BaseUrl }}/testimonials/"
[[menu.main]]
    name = "Blog"
	weight = -110
    url = "/blog/"
[[menu.main]]
weight = -100
    name = "Contact"
    url = "{{ .Site.BaseUrl }}/contact/"