baseURL = 'http://hugo-quickstart-template.netlify.com'
languageCode = 'en-us'
title = 'Sevens Legal'
theme = 'netlify-basic'
[[menu.main]]
    name = "Attorneys"
    weight = -110
    identifier = "attorneys"
    url = "/attorneys/"
[[menu.main]]
    name = "Criminal Law"
    weight = -100
    url = "/criminal/"
[[menu.main]]
    name = "Testimonials"
    weight = -100
    url = "/testimonials/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Contact"
    weight = -100
    url = "/contact/"